#!/usr/bin/bash

for f in .{bashrc,functions,bash_aliases,bash_prompt,bash_profile}; do
    [ -h ~/f ] && rm ~/$f
    ln -s ~/.dotfiles/$f ~/
done;

[ -d ~/.config/nvim ] || mkdir -p ~/.config
ln -s ~/.dotfiles/nvim ~/.config/
