#!/bin/sh

data=$(curl -s https://covid19.mohp.gov.np/covid/api/confirmedcases)

case $1 in
    '-t' | '--total')
        echo $data \
            | python -m json.tool \
            | sed -E '1,/nepal/ d; s/^\s+|[",]//g; s/:/|/; /samples|negative|positive|deaths|updated_at/b; d' \
            | awk -F "|" '
                BEGIN {print" -------------------------------------\n         all time statistics\n -------------------------------------"}
                { printf "%17s %s\n", $1,$2 }
            '
        ;;
    *)
        echo $data \
            | python -m json.tool \
            | sed -E '1,/nepal/d; s/^\s+|[",]//g; s/:/|/; s/_/ /; /today|updated at/b; d;' | sed 's/today\s\+//g' \
            | awk -F "|" '
                BEGIN {
                    print" -----------------------------------\n       statistics of last day\n -----------------------------------"
                }
                {printf "%14s %s\n", $1, $2}
            '
        ;;
esac
