#!/usr/bin/bash

outfile=${1:-~/Desktop/output.mkv}

ffmpeg \
    -f x11grab -s $(xdpyinfo | grep dimensions | awk '{ print $2}') -i :0.0 \
    -itsoffset 0.3s \
    -f alsa -i default \
    $outfile
